-- MySQL Script generated by MySQL Workbench
-- Sun May 11 15:59:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `categoria_id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `proveedor_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contacto` VARCHAR(45) NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `ruc` VARCHAR(30) NULL,
  PRIMARY KEY (`proveedor_id`),
  UNIQUE INDEX `ruc_UNIQUE` (`ruc` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `producto_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio_base` DECIMAL(10,2) NOT NULL,
  `categoria_id` INT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`producto_id`),
  INDEX `fk_producto_categoria_idx` (`categoria_id` ASC),
  INDEX `fk_producto_proveedor_idx` (`proveedor_id` ASC),
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`Categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_proveedor`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `mydb`.`Proveedor` (`proveedor_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `cliente_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Oferta` (
  `oferta_id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NOT NULL,
  `porcentaje_descuento` DECIMAL(5,2) NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `activa` TINYINT NOT NULL,
  PRIMARY KEY (`oferta_id`),
  INDEX `fk_oferta_producto_idx` (`producto_id` ASC),
  CONSTRAINT `fk_oferta_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`Producto` (`producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VarianteProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VarianteProducto` (
  `variante_id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NOT NULL,
  `talla` VARCHAR(10) NOT NULL,
  `color` VARCHAR(30) NOT NULL,
  `cantidad_stock` INT NOT NULL DEFAULT 0,
  `sku` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`variante_id`),
  INDEX `fk_variannteProducto_idx` (`producto_id` ASC),
  UNIQUE INDEX `sku_UNIQUE` (`sku` ASC),
  CONSTRAINT `fk_variannteProducto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`Producto` (`producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `empleado_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `puesto` ENUM('Vendedor', 'Supervisor', 'Gerente', 'Almacenero', 'Administrativo') NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `activo` ENUM('Activo', 'Inactivo', 'Suspendido', 'Vacaciones') NULL DEFAULT 'Activo',
  PRIMARY KEY (`empleado_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `venta_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `empleado_id` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `subtotal` DECIMAL(12,2) NOT NULL,
  `descuento_total` DECIMAL(12,2) NOT NULL DEFAULT '0.00',
  `impuesto` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `total` DECIMAL(12,2) NOT NULL,
  `metodo_pago` ENUM('EFECTIVO', 'TARJETA_CREDITO', 'TARJETA_DEBITO', 'TRANSFERENCIA', 'OTRO') NULL,
  `estado` ENUM('COMPLETADA', 'CANCELADA', 'DEVOLUCION', 'PENDIENTE') NULL,
  PRIMARY KEY (`venta_id`),
  INDEX `fk_venta_cliente_idx` (`cliente_id` ASC),
  INDEX `fk_venta_empleado_idx` (`empleado_id` ASC),
  CONSTRAINT `fk_venta_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`Cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_empleado`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `mydb`.`Empleado` (`empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetalleVenta` (
  `detalle_id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NOT NULL,
  `variante_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `descuento_unitario` DECIMAL(10,2) NULL DEFAULT 0.00,
  `total_linea` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`detalle_id`),
  INDEX `fk_detalle_venta_idx` (`venta_id` ASC),
  INDEX `fk_detalle_variante_idx` (`variante_id` ASC),
  CONSTRAINT `fk_detalle_venta`
    FOREIGN KEY (`venta_id`)
    REFERENCES `mydb`.`Venta` (`venta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_variante`
    FOREIGN KEY (`variante_id`)
    REFERENCES `mydb`.`VarianteProducto` (`variante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Configuración`
-- -----------------------------------------------------
CREATE TABLE Configuracion (
    config_id INT AUTO_INCREMENT PRIMARY KEY,
    clave VARCHAR(50) UNIQUE NOT NULL,
    valor VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255) DEFAULT NULL)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reportes` (
  `reporte_id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('Queja', 'Reclamo', 'Sugerencia', 'Reporte') NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `estado` ENUM('Abierto', 'En proceso', 'Resuelto', 'Cerrado') NULL DEFAULT 'Abierto',
  `cliente_id` INT NULL,
  `producto_id` INT NULL,
  `empleado_id` INT NULL,
  `venta_id` INT NULL,
  `fecha_cierre` DATETIME NULL,
  PRIMARY KEY (`reporte_id`),
  INDEX `fk_reporte_cliente_idx` (`cliente_id` ASC),
  INDEX `fk_reporte_producto_idx` (`producto_id` ASC),
  INDEX `fk_reporte_empleado_idx` (`empleado_id` ASC),
  INDEX `fk_reporte_venta_idx` (`venta_id` ASC),
  CONSTRAINT `fk_reporte_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`Cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`Producto` (`producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_empleado`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `mydb`.`Empleado` (`empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_venta`
    FOREIGN KEY (`venta_id`)
    REFERENCES `mydb`.`Venta` (`venta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
